<?php

namespace Enadstack\CountryData\Enums;

use Enadstack\CountryData\Enums\Concerns\RegionMethods;

// GENERATED by scripts/build-data.php from resources/regions.php — do not edit.

/**
 * Every value of a country's `filters` column. Geographic regions follow UN M49;
 * political ones are explicit membership lists — see each case, or
 * resources/regions.php for the full definitions.
 */
enum Region: string
{
    use RegionMethods;

    /** Arab League: The 22 member states of the Arab League. */
    case Arab = 'arab';

    /** Arabian Gulf: Arab states on the Arabian Gulf: the six GCC members plus Iraq. Kept as shipped since v2.0. For strict GCC membership use `gcc`. */
    case Gulf = 'gulf';

    /** Gulf Cooperation Council: The six member states of the Gulf Cooperation Council (checked 2026-09). Unlike `gulf`, it excludes Iraq. */
    case GCC = 'gcc';

    /** Levant: The Levant in its common narrow sense (Bilad al-Sham): Jordan, Lebanon, Palestine, Syria and Israel. */
    case Levant = 'levant';

    /** Maghreb: The five member states of the Arab Maghreb Union: Algeria, Libya, Mauritania, Morocco and Tunisia. */
    case Maghreb = 'maghreb';

    /** Middle East: The curated Arab Middle East set (Arab states of Western Asia plus Egypt, as shipped since v2.0) extended with Iran, Israel, Turkey and Cyprus. */
    case MiddleEast = 'middle-east';

    /** Muslim-majority: Countries and territories where Muslims are more than 50% of the population, per Pew Research Center, "The Future of the Global Muslim Population" (2011). The 22 curated countries keep their shipped tags (Lebanon is not tagged). */
    case MuslimMajority = 'muslim-majority';

    /** Africa: UN M49 region 002 "Africa". */
    case Africa = 'africa';

    /** Asia: UN M49 region 142 "Asia" (includes Western Asia, so Cyprus and Turkey are here). */
    case Asia = 'asia';

    /** Europe: UN M49 region 150 "Europe" (includes Russia; Cyprus and Turkey are in Asia per M49). */
    case Europe = 'europe';

    /** North America: The North American continent: UN M49 sub-region 021 "Northern America" plus the intermediate regions 013 "Central America" and 029 "Caribbean". */
    case NorthAmerica = 'north-america';

    /** South America: UN M49 intermediate region 005 "South America". */
    case SouthAmerica = 'south-america';

    /** Oceania: UN M49 region 009 "Oceania". */
    case Oceania = 'oceania';

    /** European Union: The 27 member states of the European Union (checked 2026-09). */
    case EU = 'eu';

    /** Schengen Area: The 29 full members of the Schengen Area, including Bulgaria and Romania since 2025-01-01 (checked 2026-09). Cyprus and Ireland are EU members outside Schengen. */
    case Schengen = 'schengen';

    /** G20: The 19 sovereign-state members of the G20 (checked 2026-09). The EU and the African Union are members too but are not countries, so they have no rows here. */
    case G20 = 'g20';

    /** @internal */
    private const META = [
        'arab' => ['label' => 'Arab League', 'kind' => 'political', 'description' => 'The 22 member states of the Arab League.'],
        'gulf' => ['label' => 'Arabian Gulf', 'kind' => 'political', 'description' => 'Arab states on the Arabian Gulf: the six GCC members plus Iraq. Kept as shipped since v2.0. For strict GCC membership use `gcc`.'],
        'gcc' => ['label' => 'Gulf Cooperation Council', 'kind' => 'political', 'description' => 'The six member states of the Gulf Cooperation Council (checked 2026-09). Unlike `gulf`, it excludes Iraq.'],
        'levant' => ['label' => 'Levant', 'kind' => 'political', 'description' => 'The Levant in its common narrow sense (Bilad al-Sham): Jordan, Lebanon, Palestine, Syria and Israel.'],
        'maghreb' => ['label' => 'Maghreb', 'kind' => 'political', 'description' => 'The five member states of the Arab Maghreb Union: Algeria, Libya, Mauritania, Morocco and Tunisia.'],
        'middle-east' => ['label' => 'Middle East', 'kind' => 'political', 'description' => 'The curated Arab Middle East set (Arab states of Western Asia plus Egypt, as shipped since v2.0) extended with Iran, Israel, Turkey and Cyprus.'],
        'muslim-majority' => ['label' => 'Muslim-majority', 'kind' => 'political', 'description' => 'Countries and territories where Muslims are more than 50% of the population, per Pew Research Center, "The Future of the Global Muslim Population" (2011). The 22 curated countries keep their shipped tags (Lebanon is not tagged).'],
        'africa' => ['label' => 'Africa', 'kind' => 'geographic', 'description' => 'UN M49 region 002 "Africa".'],
        'asia' => ['label' => 'Asia', 'kind' => 'geographic', 'description' => 'UN M49 region 142 "Asia" (includes Western Asia, so Cyprus and Turkey are here).'],
        'europe' => ['label' => 'Europe', 'kind' => 'geographic', 'description' => 'UN M49 region 150 "Europe" (includes Russia; Cyprus and Turkey are in Asia per M49).'],
        'north-america' => ['label' => 'North America', 'kind' => 'geographic', 'description' => 'The North American continent: UN M49 sub-region 021 "Northern America" plus the intermediate regions 013 "Central America" and 029 "Caribbean".'],
        'south-america' => ['label' => 'South America', 'kind' => 'geographic', 'description' => 'UN M49 intermediate region 005 "South America".'],
        'oceania' => ['label' => 'Oceania', 'kind' => 'geographic', 'description' => 'UN M49 region 009 "Oceania".'],
        'eu' => ['label' => 'European Union', 'kind' => 'political', 'description' => 'The 27 member states of the European Union (checked 2026-09).'],
        'schengen' => ['label' => 'Schengen Area', 'kind' => 'political', 'description' => 'The 29 full members of the Schengen Area, including Bulgaria and Romania since 2025-01-01 (checked 2026-09). Cyprus and Ireland are EU members outside Schengen.'],
        'g20' => ['label' => 'G20', 'kind' => 'political', 'description' => 'The 19 sovereign-state members of the G20 (checked 2026-09). The EU and the African Union are members too but are not countries, so they have no rows here.'],
    ];
}
