<?php

namespace Enadstack\CountryData\Models\Concerns;

use Enadstack\CountryData\Enums\Region;

// GENERATED by scripts/build-data.php from resources/regions.php — do not edit.

/**
 * One named scope per Region, e.g. Country::europe(), Country::gulf().
 */
trait HasRegionScopes
{
    /** Country::Arab() — Arab League. */
    public function scopeArab($query)
    {
        return $query->inRegion(Region::Arab);
    }

    /** Country::Gulf() — Arabian Gulf. */
    public function scopeGulf($query)
    {
        return $query->inRegion(Region::Gulf);
    }

    /** Country::Gcc() — Gulf Cooperation Council. */
    public function scopeGcc($query)
    {
        return $query->inRegion(Region::GCC);
    }

    /** Country::Levant() — Levant. */
    public function scopeLevant($query)
    {
        return $query->inRegion(Region::Levant);
    }

    /** Country::Maghreb() — Maghreb. */
    public function scopeMaghreb($query)
    {
        return $query->inRegion(Region::Maghreb);
    }

    /** Country::MiddleEast() — Middle East. */
    public function scopeMiddleEast($query)
    {
        return $query->inRegion(Region::MiddleEast);
    }

    /** Country::MuslimMajority() — Muslim-majority. */
    public function scopeMuslimMajority($query)
    {
        return $query->inRegion(Region::MuslimMajority);
    }

    /** Country::Africa() — Africa. */
    public function scopeAfrica($query)
    {
        return $query->inRegion(Region::Africa);
    }

    /** Country::Asia() — Asia. */
    public function scopeAsia($query)
    {
        return $query->inRegion(Region::Asia);
    }

    /** Country::Europe() — Europe. */
    public function scopeEurope($query)
    {
        return $query->inRegion(Region::Europe);
    }

    /** Country::NorthAmerica() — North America. */
    public function scopeNorthAmerica($query)
    {
        return $query->inRegion(Region::NorthAmerica);
    }

    /** Country::SouthAmerica() — South America. */
    public function scopeSouthAmerica($query)
    {
        return $query->inRegion(Region::SouthAmerica);
    }

    /** Country::Oceania() — Oceania. */
    public function scopeOceania($query)
    {
        return $query->inRegion(Region::Oceania);
    }

    /** Country::Eu() — European Union. */
    public function scopeEu($query)
    {
        return $query->inRegion(Region::EU);
    }

    /** Country::Schengen() — Schengen Area. */
    public function scopeSchengen($query)
    {
        return $query->inRegion(Region::Schengen);
    }

    /** Country::G20() — G20. */
    public function scopeG20($query)
    {
        return $query->inRegion(Region::G20);
    }
}
