<?php

namespace Enadstack\CountryData\Models\Concerns;

use Enadstack\CountryData\Enums\Region;

// GENERATED by scripts/build-data.php from resources/regions.php — do not edit.

/**
 * One named scope per Region, e.g. Country::europe(), Country::gulf().
 */
trait HasRegionScopes
{
    /** Country::arab() — Arab League. */
    public function scopeArab($query)
    {
        return $query->inRegion(Region::Arab);
    }

    /** Country::gulf() — Arabian Gulf. */
    public function scopeGulf($query)
    {
        return $query->inRegion(Region::Gulf);
    }

    /** Country::gcc() — Gulf Cooperation Council. */
    public function scopeGcc($query)
    {
        return $query->inRegion(Region::GCC);
    }

    /** Country::levant() — Levant. */
    public function scopeLevant($query)
    {
        return $query->inRegion(Region::Levant);
    }

    /** Country::maghreb() — Maghreb. */
    public function scopeMaghreb($query)
    {
        return $query->inRegion(Region::Maghreb);
    }

    /** Country::middleEast() — Middle East. */
    public function scopeMiddleEast($query)
    {
        return $query->inRegion(Region::MiddleEast);
    }

    /** Country::muslimMajority() — Muslim-majority. */
    public function scopeMuslimMajority($query)
    {
        return $query->inRegion(Region::MuslimMajority);
    }

    /** Country::africa() — Africa. */
    public function scopeAfrica($query)
    {
        return $query->inRegion(Region::Africa);
    }

    /** Country::asia() — Asia. */
    public function scopeAsia($query)
    {
        return $query->inRegion(Region::Asia);
    }

    /** Country::europe() — Europe. */
    public function scopeEurope($query)
    {
        return $query->inRegion(Region::Europe);
    }

    /** Country::northAmerica() — North America. */
    public function scopeNorthAmerica($query)
    {
        return $query->inRegion(Region::NorthAmerica);
    }

    /** Country::southAmerica() — South America. */
    public function scopeSouthAmerica($query)
    {
        return $query->inRegion(Region::SouthAmerica);
    }

    /** Country::oceania() — Oceania. */
    public function scopeOceania($query)
    {
        return $query->inRegion(Region::Oceania);
    }

    /** Country::eu() — European Union. */
    public function scopeEu($query)
    {
        return $query->inRegion(Region::EU);
    }

    /** Country::schengen() — Schengen Area. */
    public function scopeSchengen($query)
    {
        return $query->inRegion(Region::Schengen);
    }

    /** Country::g20() — G20. */
    public function scopeG20($query)
    {
        return $query->inRegion(Region::G20);
    }
}
