<?php

use Enadstack\CountryData\Support\Lookup;

/**
 * Generates the PHP that must stay in step with the data: the Region and
 * CountryCode enums, the Country region scopes, and the @method docblocks
 * that give the shortcut classes IDE autocompletion.
 */
final class CodeGenerator
{
    /** Case name for a region tag: 'north-america' → NorthAmerica, 'gcc' → GCC. */
    public static function regionCase(string $tag): string
    {
        return strlen($tag) <= 3 ? strtoupper($tag) : ucfirst(Lookup::method($tag));
    }

    public static function regionEnum(array $regions): string
    {
        $cases = $meta = '';

        foreach ($regions as $tag => $def) {
            $cases .= "    /** {$def['label']}: " . self::docLine($def['description']) . " */\n";
            $cases .= '    case ' . self::regionCase($tag) . " = '{$tag}';\n\n";
            $meta  .= "        '{$tag}' => ['label' => " . self::str($def['label'])
                    . ", 'kind' => '{$def['kind']}', 'description' => " . self::str($def['description']) . "],\n";
        }

        return <<<PHP
<?php

namespace Enadstack\\CountryData\\Enums;

use Enadstack\\CountryData\\Enums\\Concerns\\RegionMethods;

// GENERATED by scripts/build-data.php from resources/regions.php — do not edit.

/**
 * Every value of a country's `filters` column. Geographic regions follow UN M49;
 * political ones are explicit membership lists — see each case, or
 * resources/regions.php for the full definitions.
 */
enum Region: string
{
    use RegionMethods;

{$cases}    /** @internal */
    private const META = [
{$meta}    ];
}

PHP;
    }

    public static function countryCodeEnum(array $countries): string
    {
        $cases = $data = '';

        foreach ($countries as $c) {
            $cases .= "    case {$c['code']} = '{$c['code']}';  // {$c['names']['common']['en']}\n";
            $data  .= "        '{$c['code']}' => ['{$c['iso3']}', " . self::str($c['names']['common']['en'])
                    . ', ' . self::str((string) ($c['names']['common']['ar'] ?? $c['names']['common']['en'])) . "],\n";
        }

        return <<<PHP
<?php

namespace Enadstack\\CountryData\\Enums;

use Enadstack\\CountryData\\Enums\\Concerns\\CountryCodeMethods;

// GENERATED by scripts/build-data.php from data/countries.json — do not edit.

/**
 * ISO 3166-1 alpha-2 codes of every shipped country.
 *
 *   CountryCode::JO->model();      // Country row (cached)
 *   CountryCode::JO->name('ar');   // الأردن
 *   CountryCode::JO->flag();       // 🇯🇴
 *   CountryCode::fromAny('jor');   // CountryCode::JO
 */
enum CountryCode: string
{
    use CountryCodeMethods;

{$cases}
    /** @internal ISO-2 => [ISO-3, English name, Arabic name] */
    private const DATA = [
{$data}    ];
}

PHP;
    }

    public static function regionScopes(array $regions): string
    {
        $methods = '';

        foreach ($regions as $tag => $def) {
            $method   = Lookup::method($tag);
            $name     = ucfirst($method);
            $case     = self::regionCase($tag);
            $methods .= <<<PHP

    /** Country::{$method}() — {$def['label']}. */
    public function scope{$name}(\$query)
    {
        return \$query->inRegion(Region::{$case});
    }

PHP;
        }

        return <<<PHP
<?php

namespace Enadstack\\CountryData\\Models\\Concerns;

use Enadstack\\CountryData\\Enums\\Region;

// GENERATED by scripts/build-data.php from resources/regions.php — do not edit.

/**
 * One named scope per Region, e.g. Country::europe(), Country::gulf().
 */
trait HasRegionScopes
{{$methods}}

PHP;
    }

    /**
     * Replace the lines between the @generated-methods markers of a class
     * docblock with one @method tag per region and per country.
     */
    public static function injectMethods(string $source, string $regionReturn, string $countryReturn, array $regions, array $countries): string
    {
        $lines = [];

        foreach ($regions as $tag => $def) {
            $lines[] = " * @method static {$regionReturn} " . Lookup::method($tag) . "()  {$def['label']}";
        }
        foreach ($countries as $c) {
            $lines[] = " * @method static {$countryReturn} " . Lookup::method($c['names']['common']['en']) . "()  {$c['code']} {$c['names']['common']['en']}";
        }

        $block = " * @generated-methods-start\n" . implode("\n", $lines) . "\n * @generated-methods-end";

        $out = preg_replace('/ \* @generated-methods-start.*? \* @generated-methods-end/s', $block, $source, 1, $count);

        if ($count !== 1) {
            throw new RuntimeException('Missing @generated-methods markers');
        }

        return $out;
    }

    private static function str(string $s): string
    {
        return "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], $s) . "'";
    }

    private static function docLine(string $s): string
    {
        return str_replace('*/', '* /', $s);
    }
}
