<?php

/**
 * Serialises built data in the house style of the shipped files: one country
 * per block with related scalar fields grouped on a line, one city per line,
 * and short-array PHP config.
 */
final class DataFormatter
{
    private const JSON_FLAGS = JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR;

    /** Keys that share a line in countries.json, in output order. */
    private const COUNTRY_LINES = [
        ['names'],
        ['code', 'iso2', 'iso3', 'numericCode', 'cioc'],
        ['flag', 'emoji'],
        ['flags'],
        ['coatOfArms'],
        ['maps'],
        ['currency'],
        ['dial', 'capital', 'region', 'continent', 'subregion'],
        ['languages', 'timezones', 'tld', 'borders'],
        ['geo'],
        ['population', 'area'],
        ['filters'],
    ];

    public static function countriesJson(array $countries): string
    {
        $blocks = array_map(fn (array $c) => self::countryBlock($c), $countries);

        return "[\n" . implode(",\n", $blocks) . "\n]\n";
    }

    private static function countryBlock(array $country): string
    {
        $lines = [];
        $seen  = [];

        foreach (self::COUNTRY_LINES as $keys) {
            $parts = [];
            foreach ($keys as $key) {
                if (array_key_exists($key, $country)) {
                    $parts[] = self::inline($key) . ': ' . self::inline($country[$key]);
                    $seen[$key] = true;
                }
            }
            if ($parts) {
                $lines[] = '    ' . implode(', ', $parts);
            }
        }

        // Anything a future schema adds still gets written, one key per line.
        foreach ($country as $key => $value) {
            if (! isset($seen[$key])) {
                $lines[] = '    ' . self::inline($key) . ': ' . self::inline($value);
            }
        }

        return "  {\n" . implode(",\n", $lines) . "\n  }";
    }

    /**
     * Append generated city rows to the curated cities.json text, leaving every
     * curated byte untouched.
     */
    public static function appendCities(string $curatedJson, array $cities): string
    {
        if (! $cities) {
            return $curatedJson;
        }

        $end = strrpos($curatedJson, ']');
        $head = rtrim(substr($curatedJson, 0, $end));

        $rows = array_map(fn (array $c) => '  ' . self::inline($c), $cities);

        return $head . ",\n" . implode(",\n", $rows) . "\n]\n";
    }

    /** Compact single-line JSON with a space after separators. */
    public static function inline(mixed $value): string
    {
        if (! is_array($value)) {
            return json_encode($value, self::JSON_FLAGS);
        }

        if ($value === []) {
            return '[]';
        }

        if (array_is_list($value)) {
            return '[' . implode(', ', array_map([self::class, 'inline'], $value)) . ']';
        }

        $pairs = [];
        foreach ($value as $k => $v) {
            $pairs[] = json_encode((string) $k, self::JSON_FLAGS) . ': ' . self::inline($v);
        }

        return '{ ' . implode(', ', $pairs) . ' }';
    }

    // ── PHP config ──────────────────────────────────────────────────────────

    public static function countriesConfig(array $countries, string $label): string
    {
        $out  = "<?php\n\n";
        $out .= "/*\n";
        $out .= "| {$label}: " . count($countries) . " countries.\n";
        $out .= "|\n";
        $out .= "| GENERATED by scripts/build-data.php from data/countries.json's sources.\n";
        $out .= "| Do not edit by hand; edit resources/curated or resources/regions.php and rebuild.\n";
        $out .= "*/\n\n";
        $out .= "return [\n";

        foreach ($countries as $c) {
            $out .= "    // {$c['code']} — {$c['names']['common']['en']}\n";
            $out .= '    ' . self::php(self::withLegacyKeys($c), 1) . ",\n";
        }

        return $out . "];\n";
    }

    /** Keys config/countries.php carried before v2.3 (cca2 / ccn3), kept for BC. */
    private static function withLegacyKeys(array $c): array
    {
        $out = [];
        foreach ($c as $k => $v) {
            $out[$k] = $v;
            if ($k === 'cioc') {
                $out['cca2'] = $c['iso2'];
                $out['ccn3'] = $c['numericCode'];
            }
        }

        return $out;
    }

    private static function php(mixed $value, int $depth): string
    {
        if (! is_array($value)) {
            return self::phpScalar($value);
        }

        if ($value === []) {
            return '[]';
        }

        $flat = ! array_filter($value, 'is_array');

        if ($flat) {
            $items = array_is_list($value)
                ? array_map([self::class, 'phpScalar'], $value)
                : array_map(fn ($k, $v) => self::phpScalar($k) . ' => ' . self::phpScalar($v), array_keys($value), $value);

            return '[' . implode(', ', $items) . ']';
        }

        $pad   = str_repeat('    ', $depth + 1);
        $lines = [];
        foreach ($value as $k => $v) {
            $lines[] = $pad . (array_is_list($value) ? '' : self::phpScalar($k) . ' => ') . self::php($v, $depth + 1);
        }

        return "[\n" . implode(",\n", $lines) . ",\n" . str_repeat('    ', $depth) . ']';
    }

    private static function phpScalar(mixed $v): string
    {
        return match (true) {
            $v === null   => 'null',
            is_bool($v)   => $v ? 'true' : 'false',
            is_int($v)    => (string) $v,
            is_float($v)  => var_export($v, true),
            default       => "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], (string) $v) . "'",
        };
    }
}
